# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/statistdialogbase.ui'
#
# Created: Thu Nov 14 09:13:39 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_StatistDialog(object):
    def setupUi(self, StatistDialog):
        StatistDialog.setObjectName(_fromUtf8("StatistDialog"))
        StatistDialog.resize(814, 434)
        StatistDialog.setSizeGripEnabled(True)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(StatistDialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widgetStats = QtGui.QWidget(StatistDialog)
        self.widgetStats.setMinimumSize(QtCore.QSize(341, 331))
        self.widgetStats.setMaximumSize(QtCore.QSize(360, 16777215))
        self.widgetStats.setObjectName(_fromUtf8("widgetStats"))
        self.gridLayout = QtGui.QGridLayout(self.widgetStats)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widgetStats)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cmbLayers = QtGui.QComboBox(self.widgetStats)
        self.cmbLayers.setObjectName(_fromUtf8("cmbLayers"))
        self.gridLayout.addWidget(self.cmbLayers, 0, 1, 1, 2)
        self.chkUseSelected = QtGui.QCheckBox(self.widgetStats)
        self.chkUseSelected.setObjectName(_fromUtf8("chkUseSelected"))
        self.gridLayout.addWidget(self.chkUseSelected, 1, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.widgetStats)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.cmbFields = QtGui.QComboBox(self.widgetStats)
        self.cmbFields.setObjectName(_fromUtf8("cmbFields"))
        self.gridLayout.addWidget(self.cmbFields, 2, 1, 1, 2)
        self.chkUseTextFields = QtGui.QCheckBox(self.widgetStats)
        self.chkUseTextFields.setObjectName(_fromUtf8("chkUseTextFields"))
        self.gridLayout.addWidget(self.chkUseTextFields, 3, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.widgetStats)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 3)
        self.lstStatistics = QtGui.QTableWidget(self.widgetStats)
        self.lstStatistics.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lstStatistics.setAlternatingRowColors(True)
        self.lstStatistics.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lstStatistics.setWordWrap(False)
        self.lstStatistics.setCornerButtonEnabled(False)
        self.lstStatistics.setObjectName(_fromUtf8("lstStatistics"))
        self.lstStatistics.setColumnCount(2)
        self.lstStatistics.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.lstStatistics.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lstStatistics.setHorizontalHeaderItem(1, item)
        self.lstStatistics.horizontalHeader().setVisible(True)
        self.lstStatistics.horizontalHeader().setHighlightSections(False)
        self.lstStatistics.horizontalHeader().setStretchLastSection(True)
        self.lstStatistics.verticalHeader().setVisible(False)
        self.lstStatistics.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.lstStatistics, 5, 0, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(self.widgetStats)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox = QtGui.QDialogButtonBox(self.widgetStats)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 3)
        self.horizontalLayout_2.addWidget(self.widgetStats)
        self.widgetPlot = QtGui.QWidget(StatistDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPlot.sizePolicy().hasHeightForWidth())
        self.widgetPlot.setSizePolicy(sizePolicy)
        self.widgetPlot.setMinimumSize(QtCore.QSize(340, 330))
        self.widgetPlot.setObjectName(_fromUtf8("widgetPlot"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widgetPlot)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutPlot = QtGui.QVBoxLayout()
        self.layoutPlot.setObjectName(_fromUtf8("layoutPlot"))
        self.verticalLayout.addLayout(self.layoutPlot)
        self.groupBox = QtGui.QGroupBox(self.widgetPlot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.spnMinX = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnMinX.setMinimumSize(QtCore.QSize(0, 0))
        self.spnMinX.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spnMinX.setMaximum(999999999.99)
        self.spnMinX.setObjectName(_fromUtf8("spnMinX"))
        self.gridLayout_3.addWidget(self.spnMinX, 0, 1, 1, 1)
        self.btnRefresh = QtGui.QPushButton(self.groupBox)
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.gridLayout_3.addWidget(self.btnRefresh, 0, 3, 2, 1)
        self.chkShowGrid = QtGui.QCheckBox(self.groupBox)
        self.chkShowGrid.setObjectName(_fromUtf8("chkShowGrid"))
        self.gridLayout_3.addWidget(self.chkShowGrid, 0, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.spnMaxX = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnMaxX.setMinimumSize(QtCore.QSize(0, 0))
        self.spnMaxX.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spnMaxX.setMaximum(999999999.99)
        self.spnMaxX.setObjectName(_fromUtf8("spnMaxX"))
        self.gridLayout_3.addWidget(self.spnMaxX, 1, 1, 1, 1)
        self.chkAsPlot = QtGui.QCheckBox(self.groupBox)
        self.chkAsPlot.setObjectName(_fromUtf8("chkAsPlot"))
        self.gridLayout_3.addWidget(self.chkAsPlot, 1, 6, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.widgetPlot)

        self.retranslateUi(StatistDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StatistDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StatistDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StatistDialog)

    def retranslateUi(self, StatistDialog):
        StatistDialog.setWindowTitle(QtGui.QApplication.translate("StatistDialog", "Statist: Field statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("StatistDialog", "Input vector layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUseSelected.setText(QtGui.QApplication.translate("StatistDialog", "Use only selected features", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("StatistDialog", "Target field:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUseTextFields.setText(QtGui.QApplication.translate("StatistDialog", "Enable statistics for text fields", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("StatistDialog", "Statistics output:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lstStatistics.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("StatistDialog", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lstStatistics.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("StatistDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("StatistDialog", "Xmin", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefresh.setText(QtGui.QApplication.translate("StatistDialog", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowGrid.setText(QtGui.QApplication.translate("StatistDialog", "Show grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("StatistDialog", "Xmax", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAsPlot.setText(QtGui.QApplication.translate("StatistDialog", "As plot", None, QtGui.QApplication.UnicodeUTF8))

